language: php
php: 5.6

install:

script:
  - make check
  - make generate-ci

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash ci/deploy.sh

env:
  global:
    - secure: ""
